{
	"version": 1551402141,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"media/lakey inspired - chill day (vlog no copyright music).m4a",
		"media/lakey inspired - chill day (vlog no copyright music).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"aframe.min.js",
		"aframe-ar.min.js",
		"ar.min.js",
		"stats.min.js",
		"three.min.js",
		"gltfloader.js",
		"aframe-orbit-controls-component.min.js",
		"learner.html",
		"player.html",
		"inspector.html",
		"finder.html",
		"camera.svg",
		"expand.svg",
		"volume-mute.svg",
		"volume-up.svg",
		"caret-left.svg",
		"caret-right.svg",
		"map-marked-alt.svg",
		"shopping-basket.svg",
		"atlas.svg",
		"times.svg",
		"exclamation.svg",
		"fist-raised.svg",
		"coins.svg",
		"user.svg",
		"palette.svg",
		"globe-asia.svg",
		"land platform.glb",
		"water platform.glb",
		"mountain platform.glb",
		"chedi luang.glb",
		"elephant pagoda.glb",
		"grand sanctuary.glb",
		"jang sri poom.glb",
		"tha pae gate.glb",
		"three kings monument.glb",
		"village.glb",
		"tutorial0.html",
		"tutorial1.html",
		"tutorial2.html",
		"tutorial3.html",
		"tutorial4.html",
		"dpdb.json",
		"camera_para.dat",
		"arone.json",
		"_leaflet.js",
		"leaflet.css",
		"leaflet-routing-machine.css",
		"leaflet-routing-machine.js",
		"leaflet-image.js",
		"leaflet.routing.icons.png",
		"routing-icon.png"
	]
}